name: Git Flow Repository Pipeline

on:
  workflow_dispatch:

jobs:
  pipeline-testing:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Testing Step
        run: 
          echo "Testando echo na pipeline"
        shell: bash